### ISSUE TITLE
Videos denied

### ISSUE THREAD

**Issue by emilohl** [nattvara/kthGPT#36]
The following two videos were denied by kthGPT however they are part of the course DD1327:
https://www.youtube.com/watch?v=x04gACtJHX0
https://www.youtube.com/watch?v=U5KNuZGk7fQ

**Comment by nattvara** [comment]
Hi!

Thanks for opening an issue, I've added an override for those videos

Being watched now at:
- https://kthgpt.com/analyse/lectures/x04gACtJHX0/sv
- https://kthgpt.com/analyse/lectures/U5KNuZGk7fQ/sv
